---
properties:
  file:
    properties:
      contentType:
        type: "string"
      fileKey:
        type: "string"
      name:
        type: "string"
      size:
        type: "string"
    required:
    - "fileKey"
    type: "object"
  type:
    enum:
    - "FILE"
    - "PRESET"
    type: "string"
required:
- "file"
- "type"
type: "object"

