---
get:
  description: "Gets the description, name, icon, revision and color theme of an App.\n"
  operationId: "getAppSettingsForGuestSpace"
  parameters:
  - description: "guest space id"
    in: "path"
    name: "guestSpaceId"
    required: true
    schema:
      description: "guest space id"
      title: "guestSpaceId"
      type: "integer"
  - description: "The App ID.\n"
    in: "query"
    name: "app"
    required: true
    schema:
      description: "The App ID.\n"
      format: "long"
      type: "integer"
  - description: "The localized language to retrieve the data in:\n- default: retrieves\
      \ the default names\n- en: retrieves the localized English names\n- zh: retrieves\
      \ the localized Chinese names\n- ja: retrieves the localized Japanese names\n\
      - user: retrieves the localized names, in the same language as the language\
      \ setting* set on the user used for the authentication.\n\nIf ignored, the default\
      \ names will be retrieved.\n"
    in: "query"
    name: "lang"
    required: false
    schema:
      description: "The localized language to retrieve the data in:\n- default: retrieves\
        \ the default names\n- en: retrieves the localized English names\n- zh: retrieves\
        \ the localized Chinese names\n- ja: retrieves the localized Japanese names\n\
        - user: retrieves the localized names, in the same language as the language\
        \ setting* set on the user used for the authentication.\n\nIf ignored, the\
        \ default names will be retrieved.\n"
      enum:
      - "default"
      - "user"
      - "ja"
      - "en"
      - "zh"
      type: "string"
  responses:
    "200":
      description: "success case of app/settings/get"
      content:
        application/json:
          schema:
            properties:
              description:
                description: "The app description in HTML format.\n"
                maxLength: 10000
                type: "string"
              enableBulkDeletion:
                description: "The Enable bulk deletion of records setting.\n"
                type: "boolean"
              enableComments:
                description: "The Enable comments setting.\n"
                type: "boolean"
              enableDuplicateRecord:
                description: "The Enable the feature to \"duplicate record\" setting.\n"
                type: "boolean"
              enableInlineRecordEditing:
                description: "The Enable the feature to \"Inline record editing on\
                  \ record list views\" setting.\n"
                type: "boolean"
              enableThumbnails:
                description: "The Show thumbnails setting.\n"
                type: "boolean"
              firstMonthOfFiscalYear:
                description: "The First month of Fiscal Year setting. The number of\
                  \ the month will be returned.\n"
                type: "string"
              icon:
                anyOf:
                - $ref: "../openapi.yaml#/components/schemas/AppSettingsGetIconPresetForm"
                - $ref: "../openapi.yaml#/components/schemas/AppSettingsGetIconFileForm"
              name:
                description: "The App name.\n"
                maxLength: 64
                minLength: 1
                type: "string"
              numberPrecision:
                $ref: "../openapi.yaml#/components/schemas/AppSettingsGetNumberPrecision"
              revision:
                description: "The revision number of the App settings.\n"
                format: "long"
                type: "integer"
              theme:
                description: "The color theme.\n- WHITE\n- RED\n- BLUE\n- GREEN\n\
                  - YELLOW\n- BLACK\n\nApps created before February 2017 may respond\
                  \ with the following classic themes:\nCLIPBOARD, BINDER, PENCIL,\
                  \ CLIPS.\n"
                enum:
                - "WHITE"
                - "CLIPBOARD"
                - "BINDER"
                - "PENCIL"
                - "CLIPS"
                - "RED"
                - "GREEN"
                - "BLUE"
                - "YELLOW"
                - "BLACK"
                type: "string"
              titleField:
                $ref: "../openapi.yaml#/components/schemas/AppSettingsGetTitleField"
            title: "getAppSettingsForGuestSpaceResponse"
            type: "object"
  tags:
  - "APP"

