---
put:
  operationId: "putPreviewAppSettingsForGuestSpace"
  parameters:
  - description: "guest space id"
    in: "path"
    name: "guestSpaceId"
    required: true
    schema:
      description: "guest space id"
      title: "guestSpaceId"
      type: "integer"
  requestBody:
    required: true
    content:
      application/json:
        schema:
          properties:
            app:
              format: "long"
              type: "integer"
            description:
              maxLength: 10000
              type: "string"
            enableBulkDeletion:
              type: "string"
            enableComments:
              type: "string"
            enableDuplicateRecord:
              type: "string"
            enableInlineRecordEditing:
              type: "string"
            enableThumbnails:
              type: "string"
            firstMonthOfFiscalYear:
              type: "string"
            icon:
              anyOf:
              - $ref: "../openapi.yaml#/components/schemas/PreviewAppSettingsPutIconPresetForm"
              - $ref: "../openapi.yaml#/components/schemas/PreviewAppSettingsPutIconFileForm"
            name:
              maxLength: 64
              minLength: 1
              type: "string"
            numberPrecision:
              $ref: "../openapi.yaml#/components/schemas/PreviewAppSettingsPutNumberPrecision"
            revision:
              format: "long"
              type: "integer"
            theme:
              enum:
              - "WHITE"
              - "CLIPBOARD"
              - "BINDER"
              - "PENCIL"
              - "CLIPS"
              - "RED"
              - "GREEN"
              - "BLUE"
              - "YELLOW"
              - "BLACK"
              type: "string"
            titleField:
              $ref: "../openapi.yaml#/components/schemas/PreviewAppSettingsPutTitleField"
          required:
          - "app"
          title: "putPreviewAppSettingsForGuestSpaceRequest"
          type: "object"
  responses:
    "200":
      description: "success case of preview/app/settings/put"
      content:
        application/json:
          schema:
            properties:
              revision:
                format: "long"
                type: "integer"
            title: "putPreviewAppSettingsForGuestSpaceResponse"
            type: "object"
  tags:
  - "APP"
get:
  operationId: "getPreviewAppSettingsForGuestSpace"
  parameters:
  - description: "guest space id"
    in: "path"
    name: "guestSpaceId"
    required: true
    schema:
      description: "guest space id"
      title: "guestSpaceId"
      type: "integer"
  - in: "query"
    name: "app"
    required: true
    schema:
      format: "long"
      type: "integer"
  - in: "query"
    name: "lang"
    required: false
    schema:
      enum:
      - "default"
      - "user"
      - "ja"
      - "en"
      - "zh"
      type: "string"
  responses:
    "200":
      description: "success case of preview/app/settings/get"
      content:
        application/json:
          schema:
            properties:
              description:
                maxLength: 10000
                type: "string"
              enableBulkDeletion:
                type: "boolean"
              enableComments:
                type: "boolean"
              enableDuplicateRecord:
                type: "boolean"
              enableInlineRecordEditing:
                type: "boolean"
              enableThumbnails:
                type: "boolean"
              firstMonthOfFiscalYear:
                type: "string"
              icon:
                anyOf:
                - $ref: "../openapi.yaml#/components/schemas/PreviewAppSettingsGetIconPresetForm"
                - $ref: "../openapi.yaml#/components/schemas/PreviewAppSettingsGetIconFileForm"
              name:
                maxLength: 64
                minLength: 1
                type: "string"
              numberPrecision:
                $ref: "../openapi.yaml#/components/schemas/PreviewAppSettingsGetNumberPrecision"
              revision:
                format: "long"
                type: "integer"
              theme:
                enum:
                - "WHITE"
                - "CLIPBOARD"
                - "BINDER"
                - "PENCIL"
                - "CLIPS"
                - "RED"
                - "GREEN"
                - "BLUE"
                - "YELLOW"
                - "BLACK"
                type: "string"
              titleField:
                $ref: "../openapi.yaml#/components/schemas/PreviewAppSettingsGetTitleField"
            title: "getPreviewAppSettingsForGuestSpaceResponse"
            type: "object"
  tags:
  - "APP"

