name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    name: Validate yaml files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install openapi-spec-validator
      - run: find ./kintone -name "openapi.yaml" -type f | xargs openapi-spec-validator

  bundle:
    name: Check that all bundled yaml files are updated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - run: pnpm install --fetch-timeout 900000 --frozen-lockfile
      - run: pnpm bundle
      - run: git diff --stat --exit-code

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm lint

  pages:
    name: Check website build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm doc:build
