name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install openapi-spec-validator
      - run: find ./kintone -name "openapi.yaml" -type f | xargs openapi-spec-validator
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Merge OAD files
        run: |
          npm install -g swagger-merger@v1.5.4
          swagger-merger -i ./kintone/$(ls ./kintone | sort | tail -n 1)/openapi.yaml -o /tmp/openapi-merged.yaml
